# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crypto/keyspb/keyspb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crypto/keyspb/keyspb.proto',
  package='keyspb',
  syntax='proto3',
  serialized_options=_b('Z(github.com/google/trillian/crypto/keyspb'),
  serialized_pb=_b('\n\x1a\x63rypto/keyspb/keyspb.proto\x12\x06keyspb\"\xcd\x02\n\rSpecification\x12\x33\n\x0c\x65\x63\x64sa_params\x18\x01 \x01(\x0b\x32\x1b.keyspb.Specification.ECDSAH\x00\x12/\n\nrsa_params\x18\x02 \x01(\x0b\x32\x19.keyspb.Specification.RSAH\x00\x12\x37\n\x0e\x65\x64\x32\x35\x35\x31\x39_params\x18\x03 \x01(\x0b\x32\x1d.keyspb.Specification.Ed25519H\x00\x1as\n\x05\x45\x43\x44SA\x12\x30\n\x05\x63urve\x18\x01 \x01(\x0e\x32!.keyspb.Specification.ECDSA.Curve\"8\n\x05\x43urve\x12\x11\n\rDEFAULT_CURVE\x10\x00\x12\x08\n\x04P256\x10\x01\x12\x08\n\x04P384\x10\x02\x12\x08\n\x04P521\x10\x03\x1a\x13\n\x03RSA\x12\x0c\n\x04\x62its\x18\x01 \x01(\x05\x1a\t\n\x07\x45\x64\x32\x35\x35\x31\x39\x42\x08\n\x06params\",\n\nPEMKeyFile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x19\n\nPrivateKey\x12\x0b\n\x03\x64\x65r\x18\x01 \x01(\x0c\"\x18\n\tPublicKey\x12\x0b\n\x03\x64\x65r\x18\x01 \x01(\x0c\"D\n\x0cPKCS11Config\x12\x13\n\x0btoken_label\x18\x01 \x01(\t\x12\x0b\n\x03pin\x18\x02 \x01(\t\x12\x12\n\npublic_key\x18\x03 \x01(\tB*Z(github.com/google/trillian/crypto/keyspbb\x06proto3')
)



_SPECIFICATION_ECDSA_CURVE = _descriptor.EnumDescriptor(
  name='Curve',
  full_name='keyspb.Specification.ECDSA.Curve',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT_CURVE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P256', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P384', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P521', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=274,
  serialized_end=330,
)
_sym_db.RegisterEnumDescriptor(_SPECIFICATION_ECDSA_CURVE)


_SPECIFICATION_ECDSA = _descriptor.Descriptor(
  name='ECDSA',
  full_name='keyspb.Specification.ECDSA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='curve', full_name='keyspb.Specification.ECDSA.curve', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SPECIFICATION_ECDSA_CURVE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=330,
)

_SPECIFICATION_RSA = _descriptor.Descriptor(
  name='RSA',
  full_name='keyspb.Specification.RSA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bits', full_name='keyspb.Specification.RSA.bits', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=351,
)

_SPECIFICATION_ED25519 = _descriptor.Descriptor(
  name='Ed25519',
  full_name='keyspb.Specification.Ed25519',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=362,
)

_SPECIFICATION = _descriptor.Descriptor(
  name='Specification',
  full_name='keyspb.Specification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ecdsa_params', full_name='keyspb.Specification.ecdsa_params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rsa_params', full_name='keyspb.Specification.rsa_params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ed25519_params', full_name='keyspb.Specification.ed25519_params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SPECIFICATION_ECDSA, _SPECIFICATION_RSA, _SPECIFICATION_ED25519, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='params', full_name='keyspb.Specification.params',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=39,
  serialized_end=372,
)


_PEMKEYFILE = _descriptor.Descriptor(
  name='PEMKeyFile',
  full_name='keyspb.PEMKeyFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='keyspb.PEMKeyFile.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='keyspb.PEMKeyFile.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=418,
)


_PRIVATEKEY = _descriptor.Descriptor(
  name='PrivateKey',
  full_name='keyspb.PrivateKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='der', full_name='keyspb.PrivateKey.der', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=445,
)


_PUBLICKEY = _descriptor.Descriptor(
  name='PublicKey',
  full_name='keyspb.PublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='der', full_name='keyspb.PublicKey.der', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=471,
)


_PKCS11CONFIG = _descriptor.Descriptor(
  name='PKCS11Config',
  full_name='keyspb.PKCS11Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_label', full_name='keyspb.PKCS11Config.token_label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pin', full_name='keyspb.PKCS11Config.pin', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='keyspb.PKCS11Config.public_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=541,
)

_SPECIFICATION_ECDSA.fields_by_name['curve'].enum_type = _SPECIFICATION_ECDSA_CURVE
_SPECIFICATION_ECDSA.containing_type = _SPECIFICATION
_SPECIFICATION_ECDSA_CURVE.containing_type = _SPECIFICATION_ECDSA
_SPECIFICATION_RSA.containing_type = _SPECIFICATION
_SPECIFICATION_ED25519.containing_type = _SPECIFICATION
_SPECIFICATION.fields_by_name['ecdsa_params'].message_type = _SPECIFICATION_ECDSA
_SPECIFICATION.fields_by_name['rsa_params'].message_type = _SPECIFICATION_RSA
_SPECIFICATION.fields_by_name['ed25519_params'].message_type = _SPECIFICATION_ED25519
_SPECIFICATION.oneofs_by_name['params'].fields.append(
  _SPECIFICATION.fields_by_name['ecdsa_params'])
_SPECIFICATION.fields_by_name['ecdsa_params'].containing_oneof = _SPECIFICATION.oneofs_by_name['params']
_SPECIFICATION.oneofs_by_name['params'].fields.append(
  _SPECIFICATION.fields_by_name['rsa_params'])
_SPECIFICATION.fields_by_name['rsa_params'].containing_oneof = _SPECIFICATION.oneofs_by_name['params']
_SPECIFICATION.oneofs_by_name['params'].fields.append(
  _SPECIFICATION.fields_by_name['ed25519_params'])
_SPECIFICATION.fields_by_name['ed25519_params'].containing_oneof = _SPECIFICATION.oneofs_by_name['params']
DESCRIPTOR.message_types_by_name['Specification'] = _SPECIFICATION
DESCRIPTOR.message_types_by_name['PEMKeyFile'] = _PEMKEYFILE
DESCRIPTOR.message_types_by_name['PrivateKey'] = _PRIVATEKEY
DESCRIPTOR.message_types_by_name['PublicKey'] = _PUBLICKEY
DESCRIPTOR.message_types_by_name['PKCS11Config'] = _PKCS11CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Specification = _reflection.GeneratedProtocolMessageType('Specification', (_message.Message,), {

  'ECDSA' : _reflection.GeneratedProtocolMessageType('ECDSA', (_message.Message,), {
    'DESCRIPTOR' : _SPECIFICATION_ECDSA,
    '__module__' : 'crypto.keyspb.keyspb_pb2'
    # @@protoc_insertion_point(class_scope:keyspb.Specification.ECDSA)
    })
  ,

  'RSA' : _reflection.GeneratedProtocolMessageType('RSA', (_message.Message,), {
    'DESCRIPTOR' : _SPECIFICATION_RSA,
    '__module__' : 'crypto.keyspb.keyspb_pb2'
    # @@protoc_insertion_point(class_scope:keyspb.Specification.RSA)
    })
  ,

  'Ed25519' : _reflection.GeneratedProtocolMessageType('Ed25519', (_message.Message,), {
    'DESCRIPTOR' : _SPECIFICATION_ED25519,
    '__module__' : 'crypto.keyspb.keyspb_pb2'
    # @@protoc_insertion_point(class_scope:keyspb.Specification.Ed25519)
    })
  ,
  'DESCRIPTOR' : _SPECIFICATION,
  '__module__' : 'crypto.keyspb.keyspb_pb2'
  # @@protoc_insertion_point(class_scope:keyspb.Specification)
  })
_sym_db.RegisterMessage(Specification)
_sym_db.RegisterMessage(Specification.ECDSA)
_sym_db.RegisterMessage(Specification.RSA)
_sym_db.RegisterMessage(Specification.Ed25519)

PEMKeyFile = _reflection.GeneratedProtocolMessageType('PEMKeyFile', (_message.Message,), {
  'DESCRIPTOR' : _PEMKEYFILE,
  '__module__' : 'crypto.keyspb.keyspb_pb2'
  # @@protoc_insertion_point(class_scope:keyspb.PEMKeyFile)
  })
_sym_db.RegisterMessage(PEMKeyFile)

PrivateKey = _reflection.GeneratedProtocolMessageType('PrivateKey', (_message.Message,), {
  'DESCRIPTOR' : _PRIVATEKEY,
  '__module__' : 'crypto.keyspb.keyspb_pb2'
  # @@protoc_insertion_point(class_scope:keyspb.PrivateKey)
  })
_sym_db.RegisterMessage(PrivateKey)

PublicKey = _reflection.GeneratedProtocolMessageType('PublicKey', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICKEY,
  '__module__' : 'crypto.keyspb.keyspb_pb2'
  # @@protoc_insertion_point(class_scope:keyspb.PublicKey)
  })
_sym_db.RegisterMessage(PublicKey)

PKCS11Config = _reflection.GeneratedProtocolMessageType('PKCS11Config', (_message.Message,), {
  'DESCRIPTOR' : _PKCS11CONFIG,
  '__module__' : 'crypto.keyspb.keyspb_pb2'
  # @@protoc_insertion_point(class_scope:keyspb.PKCS11Config)
  })
_sym_db.RegisterMessage(PKCS11Config)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
